version: '3.9'
services:
  db:
    image: postgres:15.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRESUSER}
      - POSTGRES_PASSWORD=${POSTGRESPASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
  api:
    build:
      context: ./server/
      target: development
    image: scrumduck-server
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      NODE_ENV: development
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${POSTGRESUSER}
      DB_PASSWORD: ${POSTGRESPASSWORD}
      DB_NAME: ${POSTGRESNAME}
    links:
      - db
    volumes:
      - './:/src'
volumes:
  db:
    driver: local
